/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultPulsePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/index/vault-index.ts
var import_obsidian = require("obsidian");

// src/utils/paths.ts
function isExcludedPath(path, settings) {
  const lower = path.replace(/\\/g, "/");
  for (const folder of settings.excludeFolders) {
    const f = folder.replace(/^\/+|\/+$/g, "");
    if (!f) continue;
    if (lower === f || lower.startsWith(f + "/")) return true;
  }
  return false;
}
function archiveTargetPath(notePath, archiveFolder, now = /* @__PURE__ */ new Date()) {
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const base = notePath.split("/").pop() ?? notePath;
  const folder = `${archiveFolder.replace(/\/+$/, "")}/${y}-${m}`;
  return `${folder}/${base}`;
}

// src/utils/text.ts
function normalizeTitleKey(title) {
  return title.toLowerCase().replace(/\.md$/i, "").replace(/[^\p{L}\p{N}]+/gu, " ").trim().replace(/\s+/g, " ");
}
function normalizePrefix(text, maxLen = 120) {
  return text.replace(/\s+/g, " ").trim().slice(0, maxLen).toLowerCase();
}
function simpleHash(input) {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(16);
}
var AVOIDANCE_RE = /(?:#someday|\bsomeday\b|\btodo\b|\blater\b|나중에|언젠가|할일|미루)/i;
function hasAvoidanceMarkers(text) {
  return AVOIDANCE_RE.test(text);
}
function parentFolder(path) {
  const i = path.lastIndexOf("/");
  return i === -1 ? "" : path.slice(0, i);
}
function basenameTitle(path) {
  const base = path.split("/").pop() ?? path;
  return base.replace(/\.md$/i, "");
}
function daysBetween(fromMs, toMs) {
  return Math.floor((toMs - fromMs) / (1e3 * 60 * 60 * 24));
}
function todayKey(d = /* @__PURE__ */ new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function parseScheduleTime(hhmm) {
  const m = /^(\d{1,2}):(\d{2})$/.exec(hhmm.trim());
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (h < 0 || h > 23 || min < 0 || min > 59) return null;
  return { h, m: min };
}
function addDaysIso(days, from = /* @__PURE__ */ new Date()) {
  const d = new Date(from.getTime());
  d.setDate(d.getDate() + days);
  return d.toISOString();
}
function isSnoozed(untilIso, now = Date.now()) {
  if (!untilIso) return false;
  const t2 = Date.parse(untilIso);
  return !Number.isNaN(t2) && t2 > now;
}

// src/index/vault-index.ts
var INDEX_VERSION = 1;
var WIKILINK_RE = /\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g;
var VaultIndex = class {
  constructor(app, getSettings, persist, load) {
    this.app = app;
    this.getSettings = getSettings;
    this.persist = persist;
    this.load = load;
    this.data = {
      version: INDEX_VERSION,
      updatedAt: 0,
      notes: {}
    };
    this.building = false;
  }
  get entries() {
    return this.data.notes;
  }
  async init() {
    const loaded = await this.load();
    if (loaded?.version === INDEX_VERSION && loaded.notes) {
      this.data = loaded;
    }
    const debounced = (0, import_obsidian.debounce)(() => void this.fullRebuild(), 800, true);
    this.app.vault.on("create", (f) => {
      if (f instanceof import_obsidian.TFile && f.extension === "md") debounced();
    });
    this.app.vault.on("modify", (f) => {
      if (f instanceof import_obsidian.TFile && f.extension === "md") debounced();
    });
    this.app.vault.on("delete", (f) => {
      if (f instanceof import_obsidian.TFile && f.extension === "md") debounced();
    });
    this.app.vault.on("rename", () => debounced());
  }
  async fullRebuild() {
    if (this.building) return;
    this.building = true;
    try {
      const settings = this.getSettings();
      const files = this.app.vault.getMarkdownFiles();
      const notes = {};
      const outMap = {};
      for (const file of files) {
        if (isExcludedPath(file.path, settings)) continue;
        const content = await this.app.vault.cachedRead(file);
        const title = this.extractTitle(file, content);
        const titleKey = normalizeTitleKey(title);
        const prefix = normalizePrefix(this.stripFrontmatter(content));
        const out = this.extractOutLinks(content, file.path);
        outMap[file.path] = out;
        notes[file.path] = {
          path: file.path,
          mtime: file.stat.mtime,
          title,
          size: file.stat.size,
          outLinks: out.size,
          inLinks: 0,
          titleKey,
          prefixHash: simpleHash(prefix),
          tags: this.extractTags(content),
          hasAvoidance: hasAvoidanceMarkers(content) || hasAvoidanceMarkers(title)
        };
      }
      const pathByBasename = /* @__PURE__ */ new Map();
      for (const p of Object.keys(notes)) {
        const base = basenameTitle(p).toLowerCase();
        const arr = pathByBasename.get(base) ?? [];
        arr.push(p);
        pathByBasename.set(base, arr);
      }
      for (const [from, targets] of Object.entries(outMap)) {
        for (const raw of targets) {
          const resolved = this.resolveLink(raw, from, notes, pathByBasename);
          if (resolved && notes[resolved] && resolved !== from) {
            notes[resolved].inLinks += 1;
          }
        }
      }
      this.data = {
        version: INDEX_VERSION,
        updatedAt: Date.now(),
        notes
      };
      await this.persist(this.data);
    } finally {
      this.building = false;
    }
  }
  extractTitle(file, content) {
    const m = /^#\s+(.+)$/m.exec(content);
    if (m) return m[1].trim();
    return basenameTitle(file.path);
  }
  stripFrontmatter(content) {
    if (!content.startsWith("---")) return content;
    const end = content.indexOf("\n---", 3);
    if (end === -1) return content;
    return content.slice(end + 4);
  }
  extractTags(content) {
    const tags = /* @__PURE__ */ new Set();
    const fm = content.startsWith("---") ? content.slice(3, content.indexOf("\n---", 3) + 1) : "";
    const tagLine = /tags:\s*\[([^\]]*)\]/i.exec(fm);
    if (tagLine) {
      for (const t2 of tagLine[1].split(",")) {
        const v = t2.trim().replace(/^["']|["']$/g, "");
        if (v) tags.add(v.replace(/^#/, ""));
      }
    }
    const inline = content.matchAll(/(^|\s)#([\w\p{L}\p{N}/_-]+)/gu);
    for (const m of inline) tags.add(m[2]);
    return [...tags];
  }
  extractOutLinks(content, fromPath) {
    const set = /* @__PURE__ */ new Set();
    let m;
    const re = new RegExp(WIKILINK_RE.source, "g");
    while ((m = re.exec(content)) !== null) {
      const target = m[1].trim();
      if (target) set.add(target);
    }
    const md = content.matchAll(/\]\(([^)]+\.md)\)/gi);
    for (const x of md) set.add(x[1].replace(/^\.\//, ""));
    void fromPath;
    return set;
  }
  resolveLink(raw, fromPath, notes, pathByBasename) {
    const cleaned = raw.replace(/\\/g, "/").replace(/\.md$/i, "");
    if (notes[cleaned + ".md"]) return cleaned + ".md";
    if (notes[cleaned]) return cleaned;
    const folder = fromPath.includes("/") ? fromPath.slice(0, fromPath.lastIndexOf("/")) : "";
    const rel = folder ? `${folder}/${cleaned}.md` : `${cleaned}.md`;
    if (notes[rel]) return rel;
    const base = cleaned.split("/").pop().toLowerCase();
    const candidates = pathByBasename.get(base);
    if (candidates?.length === 1) return candidates[0];
    return null;
  }
  /** Ensure index exists; rebuild if empty */
  async ensureReady() {
    if (Object.keys(this.data.notes).length === 0) {
      await this.fullRebuild();
    }
  }
};

// src/i18n.ts
var en = {
  pluginName: "Vault Pulse",
  viewSubtitle: "Local radar for notes worth triaging. No AI. No network.",
  startSession: "Start session",
  rebuildQueue: "Rebuild queue",
  todayQueue: "Today's queue",
  emptyQueue: "No signals right now. Rescan after more notes age, or lower Stale days in settings.",
  score: "score",
  sessionTitle: "Vault Pulse session",
  remaining: "remaining",
  cardProgress: "Card {current} / {total} \xB7 processed {done}",
  queueComplete: "Queue complete. Great work \u2014 end session or wait for the timer.",
  open: "Open",
  openTooltip: "Open the note to edit. Session stays active \u2014 click the status bar to return.",
  clickToOpen: "Click to open this note",
  delete: "Delete",
  deleteTooltip: "Move note to trash (asks for confirmation)",
  deleteConfirm: "Move this note to trash?\n{path}",
  deleted: "Moved to trash: {path}",
  deleteFailed: "Could not delete note.",
  updateInfo: "Update info",
  updateInfoTooltip: "Update this note with Obsigravity (prompt first)",
  updateInfoTitle: "Update note with Obsigravity",
  updateInfoNote: "Note: {title}",
  updateInfoHint: "Describe what to update. Obsigravity will read the note and apply your request (Note Surgeon). Install via BRAT: reallygood83/obsigravity if missing.",
  updateInfoPrompt: "Your request",
  updateInfoPromptDesc: "What should change in this note?",
  updateInfoPlaceholder: "e.g. Refresh outdated facts, clarify structure, add missing tags and links\u2026",
  updateInfoRun: "Run update",
  cancel: "Cancel",
  obsigravityMissing: "Obsigravity is not installed. Install BRAT, then add reallygood83/obsigravity. Opening the note only.",
  obsigravitySoftHandoff: "Opened note + Obsigravity. Run /note-surgeon with your request if auto-start did not fire.",
  obsigravityUpdateFailed: "Obsigravity update failed. The note was opened so you can retry from Obsigravity (/note-surgeon).",
  obsigravityStarted: "Obsigravity Note Surgeon started for this note. Watch the Obsigravity panel.",
  next: "Next card",
  nextTooltip: "Done with this note for now \u2014 go to the next card (does not archive).",
  archive: "Archive",
  snooze: "Snooze",
  skip: "Skip",
  endSession: "End session",
  pauseSession: "Hide panel",
  pauseTooltip: "Hide this window. Timer keeps running. Resume from the status bar.",
  sessionHint: "Tip: Open a note to edit anytime. Closing \xD7 only hides this panel \u2014 it does NOT end the session. Use \u201CEnd session\u201D when finished.",
  sessionPaused: "Pulse session paused ({time} left). Click the status bar \u201CPulse\u201D to resume.",
  statusBarActive: "Pulse {time}",
  statusBarPaused: "Pulse \xB7 resume {time}",
  timeUp: "Pulse session time is up.",
  actionFailed: "Pulse action failed. See console.",
  cmdResume: "Resume Pulse session",
  scanning: "Vault Pulse: scanning vault\u2026",
  scanComplete: "Vault Pulse: scan complete.",
  nothingToTriage: "Vault Pulse: nothing to triage right now.",
  scheduledTime: "Vault Pulse: scheduled session starting.",
  catchUp: "Vault Pulse: catch-up session available \u2014 starting now.",
  catchUpManual: "Vault Pulse: catch-up session available. Run \u201CStart session\u201D.",
  archived: "Archived \u2192 {path}",
  sessionDone: "Pulse done: {done}/{target} \xB7 open {opened} \xB7 archive {archived} \xB7 snooze {snoozed} \xB7 skip {skipped} \xB7 streak {streak}",
  settingsTitle: "Vault Pulse",
  settingsIntro: "All processing is local. No AI. No network calls.",
  language: "Language",
  languageDesc: "UI language for Vault Pulse (English / Korean).",
  staleDays: "Stale days",
  staleDaysDesc: "Notes not modified for at least this many days can be flagged stale.",
  sessionMinutes: "Session minutes",
  sessionMinutesDesc: "Default focus session length (habit timebox).",
  sessionTarget: "Notes per day (session / queue size)",
  sessionTargetDesc: 'How many notes to queue each day. Use a number 1\u2013100, or "auto" (~session minutes \xF7 1.5, max 30). Rebuild queue after changing.',
  excludeFolders: "Exclude folders",
  excludeFoldersDesc: "Comma-separated folder prefixes to ignore (e.g. Archive, Templates).",
  archiveFolder: "Archive folder",
  archiveFolderDesc: "Archive action moves notes under this folder (year-month subfolder).",
  snoozeDays: "Snooze days",
  snoozeDaysDesc: "How long Snooze hides a note from the queue.",
  maxPerFolder: "Max notes per folder",
  maxPerFolderDesc: "Diversity cap so one folder does not fill the queue.",
  scheduleHeading: "Daily auto session",
  scheduleEnabled: "Enable daily auto session",
  scheduleEnabledDesc: "When Obsidian is open at the set local time, start a Pulse session automatically. Catch-up on next launch if you missed it.",
  scheduleTime: "Session time",
  scheduleTimeDesc: "Local 24h time, e.g. 21:00",
  scheduleAutoStart: "Auto-open session window",
  scheduleAutoStartDesc: "On: open the session modal at the scheduled time. Off: only show a notice.",
  weightsHeading: "Signal weights",
  weightStale: "Stale weight",
  weightOrphan: "Orphan weight",
  weightDuplicate: "Duplicate weight",
  weightAvoidance: "Avoidance weight",
  streakLine: "Streak: {days} day(s). Last session: {last}",
  signalStale: "Stale {days}d",
  signalOrphan: "Orphan",
  signalDuplicate: "Duplicate",
  signalAvoidance: "Avoidance",
  rootFolder: "root",
  cmdStart: "Start Pulse session",
  cmdOpenView: "Open Pulse view",
  cmdRescan: "Rescan vault index",
  howToHeading: "How to use (simple)",
  howToBody: "1) Rebuild queue \u2192 2) Click a card to open \xB7 Delete \xB7 Update info (Obsigravity) \u2192 3) Or Start session for timed triage. Closing session \xD7 only hides the panel."
};
var ko = {
  pluginName: "Vault Pulse",
  viewSubtitle: "\uC190\uB308 \uB9CC\uD55C \uB178\uD2B8\uB97C \uACE8\uB77C \uC8FC\uB294 \uB85C\uCEEC \uB808\uC774\uB354\uC785\uB2C8\uB2E4. AI \uC5C6\uC74C \xB7 \uB124\uD2B8\uC6CC\uD06C \uC5C6\uC74C.",
  startSession: "\uC138\uC158 \uC2DC\uC791",
  rebuildQueue: "\uD050 \uB2E4\uC2DC \uB9CC\uB4E4\uAE30",
  todayQueue: "\uC624\uB298\uC758 \uD050",
  emptyQueue: "\uC9C0\uAE08 \uCD94\uCC9C\uD560 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. \uB178\uD2B8\uAC00 \uB354 \uC624\uB798\uB418\uAC70\uB098, \uC124\uC815\uC5D0\uC11C \u2018\uBC29\uCE58 \uC77C\uC218\u2019\uB97C \uB0AE\uCDB0 \uBCF4\uC138\uC694.",
  score: "\uC810\uC218",
  sessionTitle: "Vault Pulse \uC138\uC158",
  remaining: "\uB0A8\uC74C",
  cardProgress: "\uCE74\uB4DC {current} / {total} \xB7 \uCC98\uB9AC {done}",
  queueComplete: "\uD050\uB97C \uBAA8\uB450 \uCC98\uB9AC\uD588\uC2B5\uB2C8\uB2E4. \uC138\uC158\uC744 \uB05D\uB0B4\uAC70\uB098 \uD0C0\uC774\uBA38\uAC00 \uB05D\uB0A0 \uB54C\uAE4C\uC9C0 \uAE30\uB2E4\uB824\uB3C4 \uB429\uB2C8\uB2E4.",
  open: "\uC5F4\uAE30",
  openTooltip: "\uB178\uD2B8\uB97C \uC5F4\uC5B4 \uC218\uC815\uD569\uB2C8\uB2E4. \uC138\uC158\uC740 \uC720\uC9C0\uB429\uB2C8\uB2E4. \uC0C1\uD0DC\uBC14\uC758 Pulse\uB97C \uB204\uB974\uBA74 \uB3CC\uC544\uC635\uB2C8\uB2E4.",
  clickToOpen: "\uD074\uB9AD\uD558\uBA74 \uB178\uD2B8\uAC00 \uC5F4\uB9BD\uB2C8\uB2E4",
  delete: "\uC0AD\uC81C",
  deleteTooltip: "\uB178\uD2B8\uB97C \uD734\uC9C0\uD1B5\uC73C\uB85C \uBCF4\uB0C5\uB2C8\uB2E4 (\uD655\uC778 \uD6C4)",
  deleteConfirm: "\uC774 \uB178\uD2B8\uB97C \uD734\uC9C0\uD1B5\uC73C\uB85C \uBCF4\uB0BC\uAE4C\uC694?\n{path}",
  deleted: "\uD734\uC9C0\uD1B5\uC73C\uB85C \uC774\uB3D9: {path}",
  deleteFailed: "\uB178\uD2B8\uB97C \uC0AD\uC81C\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.",
  updateInfo: "\uC815\uBCF4 \uC5C5\uB370\uC774\uD2B8",
  updateInfoTooltip: "Obsigravity\uB85C \uB178\uD2B8 \uC815\uBCF4 \uC5C5\uB370\uC774\uD2B8 (\uBA3C\uC800 \uC694\uCCAD \uC785\uB825)",
  updateInfoTitle: "Obsigravity\uB85C \uC815\uBCF4 \uC5C5\uB370\uC774\uD2B8",
  updateInfoNote: "\uB300\uC0C1 \uB178\uD2B8: {title}",
  updateInfoHint: "\uBB34\uC5C7\uC744 \uBC14\uAFC0\uC9C0 \uC801\uC5B4 \uC8FC\uC138\uC694. Obsigravity\uAC00 \uB178\uD2B8\uB97C \uC77D\uACE0 \uC694\uCCAD\uC5D0 \uB9DE\uAC8C \uC218\uC815\uD569\uB2C8\uB2E4(Note Surgeon). \uC5C6\uC73C\uBA74 BRAT\uB85C reallygood83/obsigravity \uC124\uCE58.",
  updateInfoPrompt: "\uC694\uCCAD \uB0B4\uC6A9",
  updateInfoPromptDesc: "\uC774 \uB178\uD2B8\uC5D0 \uC5B4\uB5A4 \uC5C5\uB370\uC774\uD2B8\uB97C \uC6D0\uD558\uB098\uC694?",
  updateInfoPlaceholder: "\uC608: \uC624\uB798\uB41C \uC0AC\uC2E4 \uC815\uB9AC, \uAD6C\uC870 \uB2E4\uB4EC\uAE30, \uD0DC\uADF8\xB7\uB9C1\uD06C \uBCF4\uAC15\u2026",
  updateInfoRun: "\uC5C5\uB370\uC774\uD2B8 \uC2E4\uD589",
  cancel: "\uCDE8\uC18C",
  obsigravityMissing: "Obsigravity\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. BRAT \uC124\uCE58 \uD6C4 reallygood83/obsigravity \uB97C \uCD94\uAC00\uD558\uC138\uC694. \uB178\uD2B8\uB9CC \uC5FD\uB2C8\uB2E4.",
  obsigravitySoftHandoff: "\uB178\uD2B8\uC640 Obsigravity\uB97C \uC5F4\uC5C8\uC2B5\uB2C8\uB2E4. \uC790\uB3D9 \uC2E4\uD589\uC774 \uC548 \uB418\uBA74 /note-surgeon \uC73C\uB85C \uC694\uCCAD\uC744 \uBCF4\uB0B4\uC138\uC694.",
  obsigravityUpdateFailed: "Obsigravity \uC5C5\uB370\uC774\uD2B8\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4. \uB178\uD2B8\uB97C \uC5F4\uC5C8\uC73C\uB2C8 Obsigravity\uC5D0\uC11C /note-surgeon \uC73C\uB85C \uB2E4\uC2DC \uC2DC\uB3C4\uD574 \uBCF4\uC138\uC694.",
  obsigravityStarted: "\uC774 \uB178\uD2B8\uC5D0 \uB300\uD574 Obsigravity Note Surgeon\uC744 \uC2DC\uC791\uD588\uC2B5\uB2C8\uB2E4. \uC624\uB978\uCABD Obsigravity \uD328\uB110\uC744 \uD655\uC778\uD558\uC138\uC694.",
  next: "\uB2E4\uC74C \uCE74\uB4DC",
  nextTooltip: "\uC774 \uB178\uD2B8\uB294 \uC77C\uB2E8 \uB05D \u2014 \uB2E4\uC74C \uCE74\uB4DC\uB85C (\uBCF4\uAD00\uD558\uC9C0 \uC54A\uC74C).",
  archive: "\uBCF4\uAD00",
  snooze: "\uB098\uC911\uC5D0",
  skip: "\uAC74\uB108\uB6F0\uAE30",
  endSession: "\uC138\uC158 \uC885\uB8CC",
  pauseSession: "\uD328\uB110 \uC228\uAE30\uAE30",
  pauseTooltip: "\uCC3D\uB9CC \uC228\uAE41\uB2C8\uB2E4. \uD0C0\uC774\uBA38\uB294 \uACC4\uC18D \uAC11\uB2C8\uB2E4. \uC0C1\uD0DC\uBC14\uC5D0\uC11C \uB2E4\uC2DC \uC5F4 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
  sessionHint: "\uD301: \u300C\uC5F4\uAE30\u300D\uB85C \uB178\uD2B8\uB97C \uC218\uC815\uD558\uC138\uC694. \xD7 \uB85C \uB2EB\uC544\uB3C4 \uC138\uC158\uC740 \uB05D\uB098\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4. \uB05D\uB0BC \uB54C\uB9CC \u300C\uC138\uC158 \uC885\uB8CC\u300D\uB97C \uB204\uB974\uC138\uC694.",
  sessionPaused: "Pulse \uC138\uC158 \uC77C\uC2DC \uC228\uAE40 (\uB0A8\uC740 \uC2DC\uAC04 {time}). \uC0C1\uD0DC\uBC14\uC758 \u201CPulse\u201D\uB97C \uB20C\uB7EC \uC774\uC5B4\uC11C \uD558\uC138\uC694.",
  statusBarActive: "Pulse {time}",
  statusBarPaused: "Pulse \xB7 \uC774\uC5B4\uD558\uAE30 {time}",
  timeUp: "Pulse \uC138\uC158 \uC2DC\uAC04\uC774 \uB05D\uB0AC\uC2B5\uB2C8\uB2E4.",
  actionFailed: "\uC791\uC5C5\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4. \uCF58\uC194\uC744 \uD655\uC778\uD574 \uC8FC\uC138\uC694.",
  cmdResume: "Pulse \uC138\uC158 \uC774\uC5B4\uD558\uAE30",
  scanning: "Vault Pulse: vault \uC2A4\uCE94 \uC911\u2026",
  scanComplete: "Vault Pulse: \uC2A4\uCE94 \uC644\uB8CC.",
  nothingToTriage: "Vault Pulse: \uC9C0\uAE08 \uC815\uB9AC\uD560 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.",
  scheduledTime: "Vault Pulse: \uC608\uC57D \uC138\uC158\uC744 \uC2DC\uC791\uD569\uB2C8\uB2E4.",
  catchUp: "Vault Pulse: \uB193\uCE5C \uC138\uC158\uC744 \uC9C0\uAE08 \uC2DC\uC791\uD569\uB2C8\uB2E4.",
  catchUpManual: "Vault Pulse: \uB193\uCE5C \uC138\uC158\uC774 \uC788\uC2B5\uB2C8\uB2E4. \u300C\uC138\uC158 \uC2DC\uC791\u300D\uC744 \uB20C\uB7EC \uC8FC\uC138\uC694.",
  archived: "\uBCF4\uAD00\uB428 \u2192 {path}",
  sessionDone: "\uC138\uC158 \uB05D: {done}/{target} \xB7 \uC5F4\uAE30 {opened} \xB7 \uBCF4\uAD00 {archived} \xB7 \uB098\uC911\uC5D0 {snoozed} \xB7 \uAC74\uB108\uB700 {skipped} \xB7 \uC5F0\uC18D {streak}\uC77C",
  settingsTitle: "Vault Pulse",
  settingsIntro: "\uBAA8\uB4E0 \uCC98\uB9AC\uB294 \uB85C\uCEEC\uC5D0\uC11C\uB9CC \uD569\uB2C8\uB2E4. AI \uC5C6\uC74C \xB7 \uB124\uD2B8\uC6CC\uD06C \uD638\uCD9C \uC5C6\uC74C.",
  language: "\uC5B8\uC5B4",
  languageDesc: "Vault Pulse \uD654\uBA74 \uC5B8\uC5B4 (\uC601\uC5B4 / \uD55C\uAD6D\uC5B4).",
  staleDays: "\uBC29\uCE58 \uC77C\uC218",
  staleDaysDesc: "\uC774 \uC77C\uC218 \uC774\uC0C1 \uC218\uC815\uD558\uC9C0 \uC54A\uC740 \uB178\uD2B8\uB97C \u2018\uC624\uB798\uB428(Stale)\u2019\uC73C\uB85C \uBCFC \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
  sessionMinutes: "\uC138\uC158 \uC2DC\uAC04(\uBD84)",
  sessionMinutesDesc: "\uD55C \uBC88 \uC9D1\uC911 \uC138\uC158 \uAE38\uC774(\uC2B5\uAD00\uC6A9 \uD0C0\uC774\uBA38).",
  sessionTarget: "\uD558\uB8E8 \uCC98\uB9AC \uB178\uD2B8 \uAC1C\uC218 (\uD050/\uC138\uC158)",
  sessionTargetDesc: '\uC624\uB298 \uD050\uC5D0 \uC62C\uB9B4 \uB178\uD2B8 \uC218. \uC22B\uC790 1\u2013100, \uB610\uB294 "auto"(\uC138\uC158 \uBD84\xF71.5, \uCD5C\uB300 30). \uBC14\uAFBC \uB4A4 \u300C\uD050 \uB2E4\uC2DC \uB9CC\uB4E4\uAE30\u300D\uB97C \uB204\uB974\uC138\uC694.',
  excludeFolders: "\uC81C\uC678 \uD3F4\uB354",
  excludeFoldersDesc: "\uBB34\uC2DC\uD560 \uD3F4\uB354 \uC811\uB450\uC0AC(\uC27C\uD45C\uB85C \uAD6C\uBD84). \uC608: Archive, Templates",
  archiveFolder: "\uBCF4\uAD00 \uD3F4\uB354",
  archiveFolderDesc: "\u300C\uBCF4\uAD00\u300D \uC2DC \uB178\uD2B8\uB97C \uC774 \uD3F4\uB354 \uC544\uB798(\uC5F0-\uC6D4 \uD558\uC704 \uD3F4\uB354)\uB85C \uC62E\uAE41\uB2C8\uB2E4.",
  snoozeDays: "\uB098\uC911\uC5D0 \uC77C\uC218",
  snoozeDaysDesc: "\u300C\uB098\uC911\uC5D0\u300D\uB97C \uB204\uB974\uBA74 \uC774 \uC77C\uC218 \uB3D9\uC548 \uD050\uC5D0\uC11C \uC228\uAE41\uB2C8\uB2E4.",
  maxPerFolder: "\uD3F4\uB354\uB2F9 \uCD5C\uB300 \uAC1C\uC218",
  maxPerFolderDesc: "\uD55C \uD3F4\uB354 \uB178\uD2B8\uAC00 \uD050\uB97C \uB3C5\uC2DD\uD558\uC9C0 \uC54A\uB3C4\uB85D \uD558\uB294 \uC0C1\uD55C.",
  scheduleHeading: "\uB9E4\uC77C \uC790\uB3D9 \uC138\uC158",
  scheduleEnabled: "\uB9E4\uC77C \uC790\uB3D9 \uC138\uC158 \uCF1C\uAE30",
  scheduleEnabledDesc: "Obsidian\uC774 \uCF1C\uC838 \uC788\uACE0 \uC124\uC815\uD55C \uC2DC\uAC01\uC774 \uB418\uBA74 Pulse \uC138\uC158\uC744 \uC790\uB3D9\uC73C\uB85C \uC5FD\uB2C8\uB2E4. \uB193\uCCE4\uB2E4\uBA74 \uB2E4\uC74C\uC5D0 \uC571\uC744 \uC5F4 \uB54C \uC774\uC5B4\uC11C \uC81C\uC548\uD569\uB2C8\uB2E4.",
  scheduleTime: "\uC138\uC158 \uC2DC\uAC01",
  scheduleTimeDesc: "\uB85C\uCEEC 24\uC2DC\uAC04 \uD615\uC2DD. \uC608: 21:00",
  scheduleAutoStart: "\uC138\uC158 \uCC3D \uC790\uB3D9\uC73C\uB85C \uC5F4\uAE30",
  scheduleAutoStartDesc: "\uCF1C\uAE30: \uC608\uC57D \uC2DC\uAC01\uC5D0 \uC138\uC158 \uCC3D\uC744 \uBC14\uB85C \uC5FD\uB2C8\uB2E4. \uB044\uAE30: \uC54C\uB9BC\uB9CC \uD45C\uC2DC\uD569\uB2C8\uB2E4.",
  weightsHeading: "\uC2E0\uD638 \uAC00\uC911\uCE58",
  weightStale: "\uC624\uB798\uB428 \uAC00\uC911\uCE58",
  weightOrphan: "\uC678\uD1A8\uC774 \uAC00\uC911\uCE58",
  weightDuplicate: "\uC911\uBCF5 \uAC00\uC911\uCE58",
  weightAvoidance: "\uBBF8\uB8F8 \uAC00\uC911\uCE58",
  streakLine: "\uC5F0\uC18D: {days}\uC77C \xB7 \uB9C8\uC9C0\uB9C9 \uC138\uC158: {last}",
  signalStale: "\uC624\uB798\uB428 {days}\uC77C",
  signalOrphan: "\uC678\uD1A8\uC774",
  signalDuplicate: "\uC911\uBCF5",
  signalAvoidance: "\uBBF8\uB8F8",
  rootFolder: "\uB8E8\uD2B8",
  cmdStart: "Pulse \uC138\uC158 \uC2DC\uC791",
  cmdOpenView: "Pulse \uBCF4\uAE30 \uC5F4\uAE30",
  cmdRescan: "vault \uC778\uB371\uC2A4 \uB2E4\uC2DC \uC2A4\uCE94",
  howToHeading: "\uC0AC\uC6A9\uBC95 (\uAC04\uB2E8)",
  howToBody: "1) \uD050 \uB2E4\uC2DC \uB9CC\uB4E4\uAE30 \u2192 2) \uCE74\uB4DC \uD074\uB9AD\uC73C\uB85C \uC5F4\uAE30 \xB7 \uC0AD\uC81C \xB7 \uC815\uBCF4 \uC5C5\uB370\uC774\uD2B8(Obsigravity) \u2192 3) \uB610\uB294 \uC138\uC158 \uC2DC\uC791\uC73C\uB85C \uD0C0\uC774\uBA38 \uC815\uB9AC. \uC138\uC158 \xD7 \uB294 \uD328\uB110\uB9CC \uC228\uAE41\uB2C8\uB2E4."
};
var TABLES = { en, ko };
function t(locale, key, vars) {
  const table = TABLES[locale] ?? en;
  let s = table[key] ?? en[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    }
  }
  return s;
}

// src/engine/scorer.ts
function buildDuplicateClusters(notes) {
  const byKey = /* @__PURE__ */ new Map();
  for (const n of Object.values(notes)) {
    if (n.titleKey) {
      const k = `t:${n.titleKey}`;
      const arr = byKey.get(k) ?? [];
      arr.push(n.path);
      byKey.set(k, arr);
    }
    if (n.prefixHash && n.size > 40) {
      const k = `p:${n.prefixHash}`;
      const arr = byKey.get(k) ?? [];
      arr.push(n.path);
      byKey.set(k, arr);
    }
  }
  const clusters = /* @__PURE__ */ new Map();
  for (const [k, paths] of byKey) {
    const uniq = [...new Set(paths)];
    if (uniq.length >= 2) clusters.set(k, uniq);
  }
  return clusters;
}
function scoreNotes(notes, settings, now = Date.now(), locale = settings.locale ?? "en") {
  const clusters = buildDuplicateClusters(notes);
  const pathToCluster = /* @__PURE__ */ new Map();
  for (const [ck, paths] of clusters) {
    for (const p of paths) {
      if (!pathToCluster.has(p) || ck.startsWith("t:")) {
        pathToCluster.set(p, ck);
      }
    }
  }
  const scored = [];
  for (const n of Object.values(notes)) {
    if (isSnoozed(settings.snoozeUntil[n.path], now)) continue;
    const daysStale = daysBetween(n.mtime, now);
    const signals = [];
    let score = 0;
    const w = settings.weights;
    if (daysStale < 3) continue;
    if (daysStale >= settings.staleDays) {
      signals.push("stale");
      const capped = Math.min(daysStale, 365);
      const staleScore = 40 * ((capped - settings.staleDays) / (365 - settings.staleDays + 1) + 0.3);
      score += w.stale * Math.min(40, Math.max(12, staleScore));
    }
    if (n.inLinks === 0) {
      signals.push("orphan");
      score += w.orphan * 30;
    }
    const ck = pathToCluster.get(n.path);
    if (ck) {
      signals.push("duplicate");
      score += w.duplicate * 25;
    }
    if (n.hasAvoidance) {
      signals.push("avoidance");
      score += w.avoidance * 10;
    }
    if (daysStale < 14) score *= 0.5;
    if (signals.length === 0 || score <= 0) continue;
    scored.push({
      path: n.path,
      title: n.title,
      score,
      signals,
      explain: buildExplain(signals, daysStale, n.inLinks, n.path, locale),
      daysStale,
      inLinks: n.inLinks,
      clusterKey: ck
    });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored;
}
function buildExplain(signals, daysStale, inLinks, path, locale) {
  const parts = [];
  if (signals.includes("stale"))
    parts.push(t(locale, "signalStale", { days: daysStale }));
  if (signals.includes("orphan")) parts.push(t(locale, "signalOrphan"));
  if (signals.includes("duplicate")) parts.push(t(locale, "signalDuplicate"));
  if (signals.includes("avoidance")) parts.push(t(locale, "signalAvoidance"));
  const folder = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
  parts.push(folder === "" ? t(locale, "rootFolder") : folder);
  void inLinks;
  return parts.join(" \xB7 ");
}

// src/engine/queue.ts
function targetCount(settings) {
  if (settings.sessionTargetCount === "auto") {
    return Math.min(30, Math.max(5, Math.floor(settings.sessionMinutes / 1.5)));
  }
  return Math.min(100, Math.max(1, settings.sessionTargetCount));
}
function buildTodayQueue(scored, settings) {
  const limit = targetCount(settings);
  const perFolder = /* @__PURE__ */ new Map();
  const perCluster = /* @__PURE__ */ new Map();
  const out = [];
  for (const note of scored) {
    if (out.length >= limit) break;
    const folder = parentFolder(note.path) || "(root)";
    const fCount = perFolder.get(folder) ?? 0;
    if (fCount >= settings.maxPerFolder) continue;
    if (note.clusterKey) {
      const c = perCluster.get(note.clusterKey) ?? 0;
      if (c >= 2) continue;
      perCluster.set(note.clusterKey, c + 1);
    }
    perFolder.set(folder, fCount + 1);
    out.push(note);
  }
  return out;
}

// src/session/schedule.ts
function shouldOfferCatchUpSession(settings, now = /* @__PURE__ */ new Date()) {
  if (!settings.scheduleEnabled) return false;
  if (settings.lastSessionDate === todayKey(now) && settings.lastSessionCompleted) {
    return false;
  }
  const t2 = parseScheduleTime(settings.scheduleTime);
  if (!t2) return false;
  const scheduled = new Date(now);
  scheduled.setHours(t2.h, t2.m, 0, 0);
  return now.getTime() >= scheduled.getTime();
}
function msUntilNextSchedule(settings, now = /* @__PURE__ */ new Date()) {
  if (!settings.scheduleEnabled) return null;
  const t2 = parseScheduleTime(settings.scheduleTime);
  if (!t2) return null;
  const next = new Date(now);
  next.setHours(t2.h, t2.m, 0, 0);
  if (next.getTime() <= now.getTime()) {
    next.setDate(next.getDate() + 1);
  }
  return next.getTime() - now.getTime();
}

// src/session/active-session.ts
var ActiveSession = class {
  constructor(queue, minutes) {
    this.index = 0;
    this.paused = false;
    this.ended = false;
    this.timerId = null;
    this.onTick = null;
    this.onTimeUp = null;
    this.queue = queue;
    this.remainingSec = Math.max(60, minutes * 60);
    this.stats = {
      opened: 0,
      archived: 0,
      snoozed: 0,
      skipped: 0,
      target: queue.length
    };
  }
  get current() {
    if (this.index >= this.queue.length) return null;
    return this.queue[this.index];
  }
  get doneCount() {
    return this.stats.opened + this.stats.archived + this.stats.snoozed + this.stats.skipped;
  }
  isSuccess() {
    return this.stats.target > 0 && this.doneCount / this.stats.target >= 0.5;
  }
  startTimer(onTick, onTimeUp) {
    this.onTick = onTick;
    this.onTimeUp = onTimeUp;
    if (this.timerId != null) window.clearInterval(this.timerId);
    this.timerId = window.setInterval(() => {
      if (this.ended) return;
      if (this.remainingSec <= 0) {
        this.stopTimer();
        this.onTimeUp?.();
        return;
      }
      this.remainingSec -= 1;
      this.onTick?.();
    }, 1e3);
  }
  stopTimer() {
    if (this.timerId != null) {
      window.clearInterval(this.timerId);
      this.timerId = null;
    }
  }
  /** Open note: count once, do NOT advance card (user may edit then return). */
  markOpened() {
    this.stats.opened += 1;
  }
  advanceAfterResolve(kind) {
    if (kind === "archive") this.stats.archived += 1;
    if (kind === "snooze") this.stats.snoozed += 1;
    if (kind === "skip") this.stats.skipped += 1;
    this.index += 1;
    return this.index >= this.queue.length;
  }
  end() {
    this.ended = true;
    this.stopTimer();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var PulseSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const L = this.plugin.settings.locale;
    const s = this.plugin.settings;
    containerEl.createEl("h2", { text: t(L, "settingsTitle") });
    containerEl.createEl("p", { text: t(L, "settingsIntro") });
    containerEl.createEl("h3", { text: t(L, "howToHeading") });
    containerEl.createEl("p", {
      cls: "pulse-muted",
      text: t(L, "howToBody")
    });
    new import_obsidian2.Setting(containerEl).setName(t(L, "language")).setDesc(t(L, "languageDesc")).addDropdown(
      (d) => d.addOption("en", "English").addOption("ko", "\uD55C\uAD6D\uC5B4").setValue(s.locale).onChange(async (v) => {
        s.locale = v === "ko" ? "ko" : "en";
        await this.plugin.saveSettings();
        this.plugin.onLocaleChange();
        this.display();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "staleDays")).setDesc(t(L, "staleDaysDesc")).addText(
      (inp) => inp.setValue(String(s.staleDays)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.staleDays = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "sessionMinutes")).setDesc(t(L, "sessionMinutesDesc")).addText(
      (inp) => inp.setValue(String(s.sessionMinutes)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.sessionMinutes = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "sessionTarget")).setDesc(t(L, "sessionTargetDesc")).addText(
      (inp) => inp.setPlaceholder("auto \uB610\uB294 1\u2013100").setValue(
        s.sessionTargetCount === "auto" ? "auto" : String(s.sessionTargetCount)
      ).onChange(async (v) => {
        const raw = v.trim().toLowerCase();
        if (raw === "auto" || raw === "") {
          s.sessionTargetCount = "auto";
        } else {
          const n = Number(raw);
          if (!Number.isNaN(n) && n > 0) {
            s.sessionTargetCount = Math.min(100, Math.max(1, Math.floor(n)));
          }
        }
        await this.plugin.saveSettings();
        await this.plugin.rebuildQueue(false);
        this.plugin.refreshOpenViewsPublic();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "excludeFolders")).setDesc(t(L, "excludeFoldersDesc")).addText(
      (inp) => inp.setValue(s.excludeFolders.join(", ")).onChange(async (v) => {
        s.excludeFolders = v.split(",").map((x) => x.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "archiveFolder")).setDesc(t(L, "archiveFolderDesc")).addText(
      (inp) => inp.setValue(s.archiveFolder).onChange(async (v) => {
        s.archiveFolder = v.trim() || "Archive/Pulse";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "snoozeDays")).setDesc(t(L, "snoozeDaysDesc")).addText(
      (inp) => inp.setValue(String(s.snoozeDays)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.snoozeDays = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "maxPerFolder")).setDesc(t(L, "maxPerFolderDesc")).addText(
      (inp) => inp.setValue(String(s.maxPerFolder)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.maxPerFolder = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: t(L, "scheduleHeading") });
    new import_obsidian2.Setting(containerEl).setName(t(L, "scheduleEnabled")).setDesc(t(L, "scheduleEnabledDesc")).addToggle(
      (tog) => tog.setValue(s.scheduleEnabled).onChange(async (v) => {
        s.scheduleEnabled = v;
        await this.plugin.saveSettings();
        this.plugin.reschedule();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "scheduleTime")).setDesc(t(L, "scheduleTimeDesc")).addText(
      (inp) => inp.setValue(s.scheduleTime).onChange(async (v) => {
        s.scheduleTime = v.trim();
        await this.plugin.saveSettings();
        this.plugin.reschedule();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t(L, "scheduleAutoStart")).setDesc(t(L, "scheduleAutoStartDesc")).addToggle(
      (tog) => tog.setValue(s.scheduleAutoStart).onChange(async (v) => {
        s.scheduleAutoStart = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t(L, "weightsHeading") });
    this.weightSetting(containerEl, s, L, "stale", "weightStale");
    this.weightSetting(containerEl, s, L, "orphan", "weightOrphan");
    this.weightSetting(containerEl, s, L, "duplicate", "weightDuplicate");
    this.weightSetting(containerEl, s, L, "avoidance", "weightAvoidance");
    containerEl.createEl("p", {
      cls: "pulse-muted",
      text: t(L, "streakLine", {
        days: s.streakDays,
        last: s.lastSessionDate || "\u2014"
      })
    });
  }
  weightSetting(containerEl, s, locale, key, nameKey) {
    new import_obsidian2.Setting(containerEl).setName(t(locale, nameKey)).addText(
      (inp) => inp.setValue(String(s.weights[key])).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n >= 0) {
          s.weights[key] = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  locale: "en",
  staleDays: 90,
  sessionMinutes: 20,
  sessionTargetCount: "auto",
  excludeFolders: ["Archive", "Templates", "attachments", ".trash"],
  archiveFolder: "Archive/Pulse",
  snoozeDays: 7,
  scheduleEnabled: false,
  scheduleTime: "21:00",
  scheduleAutoStart: true,
  weights: {
    stale: 1,
    orphan: 1,
    duplicate: 1,
    avoidance: 1
  },
  maxPerFolder: 3,
  snoozeUntil: {},
  streakDays: 0,
  lastSessionDate: "",
  lastSessionCompleted: false
};

// src/ui/session-modal.ts
var import_obsidian3 = require("obsidian");
var SessionModal = class extends import_obsidian3.Modal {
  constructor(app, handlers) {
    super(app);
    /** true when we intentionally close without ending (pause / open minimize) */
    this.suppressEnd = false;
    this.finishing = false;
    this.handlers = handlers;
    this.locale = handlers.locale;
    this.session = handlers.session;
  }
  onOpen() {
    const { contentEl } = this;
    const L = this.locale;
    contentEl.empty();
    contentEl.addClass("pulse-session-modal");
    contentEl.createEl("h2", { text: t(L, "sessionTitle") });
    this.timerEl = contentEl.createDiv({ cls: "pulse-timer" });
    this.statusEl = contentEl.createDiv({ cls: "pulse-status" });
    this.hintEl = contentEl.createDiv({ cls: "pulse-hint pulse-muted" });
    this.hintEl.setText(t(L, "sessionHint"));
    this.cardEl = contentEl.createDiv({ cls: "pulse-card" });
    const actions = contentEl.createDiv({ cls: "pulse-actions" });
    new import_obsidian3.Setting(actions).addButton(
      (b) => b.setButtonText(t(L, "open")).setCta().setTooltip(t(L, "openTooltip")).onClick(() => void this.act("open"))
    ).addButton(
      (b) => b.setButtonText(t(L, "next")).setTooltip(t(L, "nextTooltip")).onClick(() => void this.act("next"))
    ).addButton(
      (b) => b.setButtonText(t(L, "archive")).onClick(() => void this.act("archive"))
    ).addButton(
      (b) => b.setButtonText(t(L, "snooze")).onClick(() => void this.act("snooze"))
    ).addButton(
      (b) => b.setButtonText(t(L, "skip")).onClick(() => void this.act("skip"))
    );
    const footer = contentEl.createDiv({ cls: "pulse-footer-actions" });
    new import_obsidian3.Setting(footer).addButton(
      (b) => b.setButtonText(t(L, "pauseSession")).setTooltip(t(L, "pauseTooltip")).onClick(() => this.pauseAndClose())
    ).addButton(
      (b) => b.setButtonText(t(L, "endSession")).setWarning().onClick(() => this.requestEnd(false))
    );
    this.refresh();
    this.session.startTimer(
      () => this.refreshTimerOnly(),
      () => this.requestEnd(true)
    );
  }
  onClose() {
    if (this.finishing) return;
    if (this.suppressEnd) {
      this.suppressEnd = false;
      return;
    }
    this.handlers.onPause();
  }
  /** Public: refresh after resume or action */
  refresh() {
    this.refreshTimerOnly();
    this.renderCard();
  }
  refreshTimerOnly() {
    const sec = this.session.remainingSec;
    const m = Math.floor(Math.max(0, sec) / 60);
    const s = Math.max(0, sec) % 60;
    if (this.timerEl) {
      this.timerEl.setText(
        `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")} ${t(this.locale, "remaining")}`
      );
    }
    if (this.statusEl) {
      this.statusEl.setText(
        t(this.locale, "cardProgress", {
          current: Math.min(
            this.session.index + 1,
            this.session.queue.length
          ),
          total: this.session.queue.length,
          done: this.session.doneCount
        })
      );
    }
  }
  renderCard() {
    const L = this.locale;
    if (!this.cardEl) return;
    this.cardEl.empty();
    const note = this.session.current;
    if (!note) {
      this.cardEl.createEl("p", { text: t(L, "queueComplete") });
      return;
    }
    this.cardEl.createEl("h3", { text: note.title });
    this.cardEl.createEl("p", { cls: "pulse-explain", text: note.explain });
    this.cardEl.createEl("p", { cls: "pulse-path", text: note.path });
  }
  async act(action) {
    const note = this.session.current;
    if (!note && action !== "end") return;
    try {
      if (note) await this.handlers.onAction(note, action);
    } catch (e) {
      console.error(e);
      return;
    }
    if (action === "open") {
      this.pauseAndClose();
      return;
    }
    if (action === "archive" || action === "snooze" || action === "skip" || action === "next") {
      const finished = this.session.advanceAfterResolve(
        action === "next" ? "done" : action
      );
      if (finished) {
        this.requestEnd(false);
        return;
      }
      this.refresh();
    }
  }
  pauseAndClose() {
    this.suppressEnd = true;
    this.session.paused = true;
    this.handlers.onPause();
    this.close();
  }
  requestEnd(auto) {
    if (this.finishing) return;
    this.finishing = true;
    this.suppressEnd = true;
    this.handlers.onRequestEnd(auto);
    this.close();
  }
};

// src/ui/pulse-view.ts
var import_obsidian4 = require("obsidian");
var PULSE_VIEW_TYPE = "vault-pulse-view";
var PulseView = class extends import_obsidian4.ItemView {
  constructor(leaf) {
    super(leaf);
    this.queue = [];
    this.locale = "en";
    this.onStart = null;
    this.onRefresh = null;
    this.onOpenNote = null;
    this.onDeleteNote = null;
    this.onUpdateInfo = null;
  }
  getViewType() {
    return PULSE_VIEW_TYPE;
  }
  getDisplayText() {
    return "Vault Pulse";
  }
  getIcon() {
    return "activity";
  }
  setHandlers(opts) {
    this.onStart = opts.onStart;
    this.onRefresh = opts.onRefresh;
    this.onOpenNote = opts.onOpenNote;
    this.onDeleteNote = opts.onDeleteNote;
    this.onUpdateInfo = opts.onUpdateInfo;
  }
  setLocale(locale) {
    this.locale = locale;
    this.render();
  }
  setQueue(queue) {
    this.queue = queue;
    this.render();
  }
  async onOpen() {
    this.render();
  }
  render() {
    const L = this.locale;
    const root = this.contentEl;
    root.empty();
    root.addClass("pulse-view");
    root.createEl("h2", { text: t(L, "pluginName") });
    root.createEl("p", {
      cls: "pulse-muted",
      text: t(L, "viewSubtitle")
    });
    const toolbar = root.createDiv({ cls: "pulse-toolbar" });
    const startBtn = toolbar.createEl("button", {
      text: t(L, "startSession"),
      cls: "mod-cta"
    });
    startBtn.onclick = () => this.onStart?.();
    const refreshBtn = toolbar.createEl("button", {
      text: t(L, "rebuildQueue")
    });
    refreshBtn.onclick = () => void this.onRefresh?.();
    root.createEl("h3", {
      text: `${t(L, "todayQueue")} (${this.queue.length})`
    });
    if (this.queue.length === 0) {
      root.createEl("p", { text: t(L, "emptyQueue") });
      return;
    }
    const list = root.createEl("ul", { cls: "pulse-queue-list" });
    for (const n of this.queue) {
      const li = list.createEl("li");
      li.addClass("pulse-queue-item");
      const body = li.createDiv({ cls: "pulse-q-body" });
      body.setAttr("role", "button");
      body.setAttr("tabindex", "0");
      body.setAttr("title", t(L, "clickToOpen"));
      body.onclick = (e) => {
        e.preventDefault();
        this.onOpenNote?.(n.path);
      };
      body.onkeydown = (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          this.onOpenNote?.(n.path);
        }
      };
      const title = body.createEl("div", {
        cls: "pulse-q-title",
        text: n.title
      });
      title.setAttr("title", n.path);
      body.createEl("div", { cls: "pulse-q-explain", text: n.explain });
      body.createEl("div", {
        cls: "pulse-q-score",
        text: `${t(L, "score")} ${n.score.toFixed(1)}`
      });
      const actions = li.createDiv({ cls: "pulse-q-actions" });
      const openBtn = actions.createEl("button", {
        text: t(L, "open"),
        cls: "pulse-mini-btn"
      });
      openBtn.onclick = (e) => {
        e.stopPropagation();
        this.onOpenNote?.(n.path);
      };
      const updateBtn = actions.createEl("button", {
        text: t(L, "updateInfo"),
        cls: "pulse-mini-btn mod-cta"
      });
      updateBtn.setAttr("title", t(L, "updateInfoTooltip"));
      updateBtn.onclick = (e) => {
        e.stopPropagation();
        this.onUpdateInfo?.(n.path, n.title);
      };
      const delBtn = actions.createEl("button", {
        text: t(L, "delete"),
        cls: "pulse-mini-btn pulse-danger"
      });
      delBtn.setAttr("title", t(L, "deleteTooltip"));
      delBtn.onclick = (e) => {
        e.stopPropagation();
        this.onDeleteNote?.(n.path);
      };
    }
  }
};

// src/ui/update-info-modal.ts
var import_obsidian5 = require("obsidian");
var UpdateInfoModal = class extends import_obsidian5.Modal {
  constructor(app, opts) {
    super(app);
    this.input = "";
    this.locale = opts.locale;
    this.noteTitle = opts.noteTitle;
    this.notePath = opts.notePath;
    this.onSubmit = opts.onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    const L = this.locale;
    contentEl.empty();
    contentEl.addClass("pulse-update-modal");
    contentEl.createEl("h2", { text: t(L, "updateInfoTitle") });
    contentEl.createEl("p", {
      cls: "pulse-muted",
      text: t(L, "updateInfoNote", { title: this.noteTitle })
    });
    contentEl.createEl("p", {
      cls: "pulse-path",
      text: this.notePath
    });
    contentEl.createEl("p", {
      cls: "pulse-muted",
      text: t(L, "updateInfoHint")
    });
    let area = null;
    new import_obsidian5.Setting(contentEl).setName(t(L, "updateInfoPrompt")).setDesc(t(L, "updateInfoPromptDesc")).addTextArea((ta) => {
      area = ta;
      ta.setPlaceholder(t(L, "updateInfoPlaceholder"));
      ta.inputEl.rows = 6;
      ta.inputEl.style.width = "100%";
      ta.onChange((v) => {
        this.input = v;
      });
    });
    new import_obsidian5.Setting(contentEl).addButton(
      (b) => b.setButtonText(t(L, "cancel")).onClick(() => this.close())
    ).addButton(
      (b) => b.setButtonText(t(L, "updateInfoRun")).setCta().onClick(() => {
        const text = this.input.trim() || area?.getValue().trim() || "";
        if (!text) {
          return;
        }
        this.close();
        this.onSubmit(text);
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/obsigravity-bridge.ts
var import_obsidian6 = require("obsidian");
var OBSIGRAVITY_ID = "obsigravity";
var BRAT_URL = "https://github.com/TfTHacker/obsidian42-brat";
var OBSIGRAVITY_REPO = "https://github.com/reallygood83/obsigravity";
function getObsigravity(app) {
  const plugins = app.plugins;
  if (!plugins) return null;
  const p = plugins.getPlugin?.(OBSIGRAVITY_ID) || plugins.plugins?.[OBSIGRAVITY_ID] || null;
  return p ?? null;
}
function showObsigravityInstallGuide(locale) {
  new import_obsidian6.Notice(t(locale, "obsigravityMissing"), 12e3);
  console.info(
    `[Vault Pulse] Install Obsigravity via BRAT:
1) Install BRAT: ${BRAT_URL}
2) Add plugin: reallygood83/obsigravity
3) Repo: ${OBSIGRAVITY_REPO}`
  );
}
async function runInfoUpdate(app, locale, notePath, userPrompt) {
  const og = getObsigravity(app);
  if (!og) {
    showObsigravityInstallGuide(locale);
    const file = app.vault.getAbstractFileByPath(notePath);
    if (file instanceof import_obsidian6.TFile) {
      await app.workspace.getLeaf(false).openFile(file);
    }
    return;
  }
  const target = app.vault.getAbstractFileByPath(notePath);
  if (target instanceof import_obsidian6.TFile) {
    await app.workspace.getLeaf(false).openFile(target, { active: true });
  }
  if (typeof og.startNoteUpdateFromPulse === "function") {
    try {
      await og.startNoteUpdateFromPulse(notePath, userPrompt);
      new import_obsidian6.Notice(t(locale, "obsigravityStarted"), 6e3);
    } catch (e) {
      console.error("[Vault Pulse] Obsigravity update failed", e);
      new import_obsidian6.Notice(t(locale, "obsigravityUpdateFailed"), 8e3);
    }
    return;
  }
  try {
    if (typeof og.queuePulseUpdate === "function") {
      og.queuePulseUpdate(notePath, userPrompt);
    }
    const file = app.vault.getAbstractFileByPath(notePath);
    if (file instanceof import_obsidian6.TFile) {
      await app.workspace.getLeaf(false).openFile(file);
    }
    if (typeof og.activateView === "function") {
      await og.activateView();
    }
    try {
      await app.commands.executeCommandById(
        "obsigravity:update-note-from-pulse"
      );
    } catch {
    }
    new import_obsidian6.Notice(t(locale, "obsigravitySoftHandoff"), 8e3);
  } catch (e) {
    console.error("[Vault Pulse] Obsigravity soft handoff failed", e);
    new import_obsidian6.Notice(t(locale, "obsigravityUpdateFailed"), 8e3);
  }
}

// src/main.ts
var VaultPulsePlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = {
      ...DEFAULT_SETTINGS,
      weights: { ...DEFAULT_SETTINGS.weights },
      snoozeUntil: {},
      excludeFolders: [...DEFAULT_SETTINGS.excludeFolders]
    };
    this.scheduleTimer = null;
    this.cachedQueue = [];
    /** Live session (survives modal close) */
    this.active = null;
    this.modal = null;
    this.statusEl = null;
    this.statusTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.index = new VaultIndex(
      this.app,
      () => this.settings,
      async (data) => {
        await this.saveData({
          settings: this.settings,
          index: data
        });
      },
      async () => {
        const raw = await this.loadData();
        return raw?.index ?? null;
      }
    );
    await this.index.init();
    this.registerView(PULSE_VIEW_TYPE, (leaf) => {
      const view = new PulseView(leaf);
      view.setLocale(this.settings.locale);
      view.setHandlers({
        onStart: () => void this.startSession(),
        onRefresh: async () => {
          await this.rebuildQueue(true);
          this.refreshOpenViews();
        },
        onOpenNote: (path) => void this.openNotePath(path),
        onDeleteNote: (path) => void this.deleteNotePath(path),
        onUpdateInfo: (path, title) => this.openUpdateInfoModal(path, title)
      });
      return view;
    });
    this.addRibbonIcon("activity", "Vault Pulse", () => {
      if (this.active && !this.active.ended) {
        this.resumeSession();
      } else {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "pulse-start-session",
      name: t(this.settings.locale, "cmdStart"),
      callback: () => void this.startSession()
    });
    this.addCommand({
      id: "pulse-resume-session",
      name: t(this.settings.locale, "cmdResume"),
      checkCallback: (checking) => {
        const ok = !!(this.active && !this.active.ended);
        if (ok && !checking) this.resumeSession();
        return ok;
      }
    });
    this.addCommand({
      id: "pulse-open-view",
      name: t(this.settings.locale, "cmdOpenView"),
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "pulse-rescan",
      name: t(this.settings.locale, "cmdRescan"),
      callback: () => void this.rescan()
    });
    this.addSettingTab(new PulseSettingTab(this.app, this));
    this.statusEl = this.addStatusBarItem();
    this.statusEl.addClass("pulse-status-bar");
    this.statusEl.hide();
    this.statusEl.onclick = () => this.resumeSession();
    void this.app.workspace.onLayoutReady(async () => {
      await this.index.ensureReady();
      await this.rebuildQueue(false);
      this.refreshOpenViews();
      this.reschedule();
      if (shouldOfferCatchUpSession(this.settings)) {
        if (this.settings.scheduleAutoStart) {
          new import_obsidian7.Notice(t(this.settings.locale, "catchUp"));
          window.setTimeout(() => void this.startSession(), 600);
        } else {
          new import_obsidian7.Notice(t(this.settings.locale, "catchUpManual"));
        }
      }
    });
  }
  onunload() {
    if (this.scheduleTimer != null) {
      window.clearTimeout(this.scheduleTimer);
      this.scheduleTimer = null;
    }
    this.clearStatusBar();
    if (this.active) {
      this.active.end();
      this.active = null;
    }
    this.modal = null;
    for (const leaf of this.app.workspace.getLeavesOfType(PULSE_VIEW_TYPE)) {
      leaf.detach();
    }
  }
  async loadSettings() {
    const raw = await this.loadData();
    if (raw?.settings) {
      this.settings = {
        ...DEFAULT_SETTINGS,
        ...raw.settings,
        locale: raw.settings.locale === "ko" ? "ko" : "en",
        scheduleAutoStart: raw.settings.scheduleAutoStart ?? DEFAULT_SETTINGS.scheduleAutoStart,
        weights: { ...DEFAULT_SETTINGS.weights, ...raw.settings.weights },
        excludeFolders: raw.settings.excludeFolders ?? [...DEFAULT_SETTINGS.excludeFolders],
        snoozeUntil: raw.settings.snoozeUntil ?? {}
      };
    }
  }
  async saveSettings() {
    const raw = await this.loadData();
    await this.saveData({
      settings: this.settings,
      index: raw?.index ?? null
    });
  }
  onLocaleChange() {
    void this.rebuildQueue(false).then(() => this.refreshOpenViews());
  }
  reschedule() {
    if (this.scheduleTimer != null) {
      window.clearTimeout(this.scheduleTimer);
      this.scheduleTimer = null;
    }
    if (!this.settings.scheduleEnabled) return;
    const ms = msUntilNextSchedule(this.settings);
    if (ms == null) return;
    this.scheduleTimer = window.setTimeout(() => {
      void this.onScheduledFire();
      this.reschedule();
    }, ms);
  }
  async onScheduledFire() {
    const L = this.settings.locale;
    if (this.settings.lastSessionDate === todayKey() && this.settings.lastSessionCompleted) {
      return;
    }
    new import_obsidian7.Notice(t(L, "scheduledTime"));
    if (this.settings.scheduleAutoStart) {
      await this.startSession();
    }
  }
  async rescan() {
    const L = this.settings.locale;
    new import_obsidian7.Notice(t(L, "scanning"));
    await this.index.fullRebuild();
    await this.rebuildQueue(false);
    this.refreshOpenViews();
    new import_obsidian7.Notice(t(L, "scanComplete"));
  }
  async rebuildQueue(forceRescan) {
    if (forceRescan) await this.index.fullRebuild();
    else await this.index.ensureReady();
    const scored = scoreNotes(
      this.index.entries,
      this.settings,
      Date.now(),
      this.settings.locale
    );
    this.cachedQueue = buildTodayQueue(scored, this.settings);
  }
  /** Used by settings tab after changing daily note count */
  refreshOpenViewsPublic() {
    this.refreshOpenViews();
  }
  refreshOpenViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(PULSE_VIEW_TYPE)) {
      const v = leaf.view;
      if (v instanceof PulseView) {
        v.setLocale(this.settings.locale);
        v.setQueue(this.cachedQueue);
      }
    }
  }
  async openNotePath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian7.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    }
  }
  async deleteNotePath(path) {
    const L = this.settings.locale;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian7.TFile)) {
      new import_obsidian7.Notice(t(L, "deleteFailed"));
      return;
    }
    const ok = window.confirm(t(L, "deleteConfirm", { path }));
    if (!ok) return;
    try {
      await this.app.vault.trash(file, true);
      new import_obsidian7.Notice(t(L, "deleted", { path }));
      await this.rebuildQueue(true);
      this.refreshOpenViews();
    } catch (e) {
      console.error(e);
      new import_obsidian7.Notice(t(L, "deleteFailed"));
    }
  }
  openUpdateInfoModal(path, title) {
    const L = this.settings.locale;
    new UpdateInfoModal(this.app, {
      locale: L,
      noteTitle: title,
      notePath: path,
      onSubmit: (prompt) => {
        void runInfoUpdate(this.app, L, path, prompt);
      }
    }).open();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(PULSE_VIEW_TYPE);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf?.setViewState({ type: PULSE_VIEW_TYPE, active: true });
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      await this.rebuildQueue(false);
      this.refreshOpenViews();
    }
  }
  async startSession() {
    if (this.active && !this.active.ended) {
      this.resumeSession();
      return;
    }
    await this.rebuildQueue(false);
    const L = this.settings.locale;
    if (this.cachedQueue.length === 0) {
      new import_obsidian7.Notice(t(L, "nothingToTriage"));
      return;
    }
    this.active = new ActiveSession(
      [...this.cachedQueue],
      this.settings.sessionMinutes
    );
    this.showStatusBar();
    this.openSessionModal();
  }
  resumeSession() {
    if (!this.active || this.active.ended) {
      void this.startSession();
      return;
    }
    this.active.paused = false;
    this.showStatusBar();
    this.openSessionModal();
  }
  openSessionModal() {
    if (!this.active || this.active.ended) return;
    if (this.modal) {
      try {
        this.modal.close();
      } catch {
      }
      this.modal = null;
    }
    const session = this.active;
    const modal = new SessionModal(this.app, {
      locale: this.settings.locale,
      session,
      onAction: (note, action) => this.handleAction(note, action),
      onPause: () => this.onSessionPaused(),
      onRequestEnd: (auto) => this.endActiveSession(auto)
    });
    this.modal = modal;
    modal.open();
  }
  onSessionPaused() {
    if (!this.active || this.active.ended) return;
    this.active.paused = true;
    this.modal = null;
    this.showStatusBar();
    const time = this.formatTime(this.active.remainingSec);
    new import_obsidian7.Notice(t(this.settings.locale, "sessionPaused", { time }));
  }
  endActiveSession(auto) {
    if (!this.active) return;
    const stats = { ...this.active.stats };
    const completed = this.active.isSuccess();
    this.active.end();
    this.active = null;
    this.modal = null;
    this.clearStatusBar();
    if (auto) new import_obsidian7.Notice(t(this.settings.locale, "timeUp"));
    void this.finishSession(stats, completed);
  }
  formatTime(sec) {
    const m = Math.floor(Math.max(0, sec) / 60);
    const s = Math.max(0, sec) % 60;
    return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  }
  showStatusBar() {
    if (!this.statusEl || !this.active) return;
    this.statusEl.show();
    this.updateStatusBar();
    if (this.statusTimer != null) window.clearInterval(this.statusTimer);
    this.statusTimer = window.setInterval(() => this.updateStatusBar(), 1e3);
  }
  updateStatusBar() {
    if (!this.statusEl || !this.active || this.active.ended) {
      this.clearStatusBar();
      return;
    }
    const time = this.formatTime(this.active.remainingSec);
    const key = this.active.paused ? "statusBarPaused" : "statusBarActive";
    this.statusEl.setText(t(this.settings.locale, key, { time }));
    this.statusEl.setAttr(
      "aria-label",
      t(this.settings.locale, "cmdResume")
    );
  }
  clearStatusBar() {
    if (this.statusTimer != null) {
      window.clearInterval(this.statusTimer);
      this.statusTimer = null;
    }
    if (this.statusEl) {
      this.statusEl.setText("");
      this.statusEl.hide();
    }
  }
  async handleAction(note, action) {
    const L = this.settings.locale;
    if (!this.active) return;
    if (action === "open") {
      const file = this.app.vault.getAbstractFileByPath(note.path);
      if (file instanceof import_obsidian7.TFile) {
        await this.app.workspace.getLeaf(false).openFile(file);
      }
      this.active.markOpened();
      return;
    }
    if (action === "next") {
      return;
    }
    if (action === "snooze") {
      this.settings.snoozeUntil[note.path] = addDaysIso(
        this.settings.snoozeDays
      );
      await this.saveSettings();
      return;
    }
    if (action === "skip") return;
    if (action === "archive") {
      const file = this.app.vault.getAbstractFileByPath(note.path);
      if (!(file instanceof import_obsidian7.TFile)) return;
      const dest = archiveTargetPath(note.path, this.settings.archiveFolder);
      const folder = dest.slice(0, dest.lastIndexOf("/"));
      await this.ensureFolder(folder);
      let finalDest = dest;
      if (this.app.vault.getAbstractFileByPath(finalDest)) {
        const stamp = Date.now();
        const base = note.path.split("/").pop().replace(/\.md$/i, "");
        finalDest = `${folder}/${base}-${stamp}.md`;
      }
      await this.app.fileManager.renameFile(file, finalDest);
      new import_obsidian7.Notice(t(L, "archived", { path: finalDest }));
    }
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let cur = "";
    for (const p of parts) {
      cur = cur ? `${cur}/${p}` : p;
      if (!this.app.vault.getAbstractFileByPath(cur)) {
        await this.app.vault.createFolder(cur);
      }
    }
  }
  async finishSession(stats, completed) {
    const today = todayKey();
    if (completed) {
      if (this.settings.lastSessionDate !== today) {
        const yesterday = /* @__PURE__ */ new Date();
        yesterday.setDate(yesterday.getDate() - 1);
        if (this.settings.lastSessionDate === todayKey(yesterday)) {
          this.settings.streakDays += 1;
        } else {
          this.settings.streakDays = 1;
        }
      }
    }
    this.settings.lastSessionDate = today;
    this.settings.lastSessionCompleted = completed;
    await this.saveSettings();
    await this.rebuildQueue(false);
    this.refreshOpenViews();
    const done = stats.opened + stats.archived + stats.snoozed + stats.skipped;
    new import_obsidian7.Notice(
      t(this.settings.locale, "sessionDone", {
        done,
        target: stats.target,
        opened: stats.opened,
        archived: stats.archived,
        snoozed: stats.snoozed,
        skipped: stats.skipped,
        streak: this.settings.streakDays
      })
    );
  }
};
