/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultPulsePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/index/vault-index.ts
var import_obsidian = require("obsidian");

// src/utils/paths.ts
function isExcludedPath(path, settings) {
  const lower = path.replace(/\\/g, "/");
  for (const folder of settings.excludeFolders) {
    const f = folder.replace(/^\/+|\/+$/g, "");
    if (!f) continue;
    if (lower === f || lower.startsWith(f + "/")) return true;
  }
  return false;
}
function archiveTargetPath(notePath, archiveFolder, now = /* @__PURE__ */ new Date()) {
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const base = notePath.split("/").pop() ?? notePath;
  const folder = `${archiveFolder.replace(/\/+$/, "")}/${y}-${m}`;
  return `${folder}/${base}`;
}

// src/utils/text.ts
function normalizeTitleKey(title) {
  return title.toLowerCase().replace(/\.md$/i, "").replace(/[^\p{L}\p{N}]+/gu, " ").trim().replace(/\s+/g, " ");
}
function normalizePrefix(text, maxLen = 120) {
  return text.replace(/\s+/g, " ").trim().slice(0, maxLen).toLowerCase();
}
function simpleHash(input) {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(16);
}
var AVOIDANCE_RE = /(?:#someday|\bsomeday\b|\btodo\b|\blater\b|나중에|언젠가|할일|미루)/i;
function hasAvoidanceMarkers(text) {
  return AVOIDANCE_RE.test(text);
}
function parentFolder(path) {
  const i = path.lastIndexOf("/");
  return i === -1 ? "" : path.slice(0, i);
}
function basenameTitle(path) {
  const base = path.split("/").pop() ?? path;
  return base.replace(/\.md$/i, "");
}
function daysBetween(fromMs, toMs) {
  return Math.floor((toMs - fromMs) / (1e3 * 60 * 60 * 24));
}
function todayKey(d = /* @__PURE__ */ new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function parseScheduleTime(hhmm) {
  const m = /^(\d{1,2}):(\d{2})$/.exec(hhmm.trim());
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (h < 0 || h > 23 || min < 0 || min > 59) return null;
  return { h, m: min };
}
function addDaysIso(days, from = /* @__PURE__ */ new Date()) {
  const d = new Date(from.getTime());
  d.setDate(d.getDate() + days);
  return d.toISOString();
}
function isSnoozed(untilIso, now = Date.now()) {
  if (!untilIso) return false;
  const t = Date.parse(untilIso);
  return !Number.isNaN(t) && t > now;
}

// src/index/vault-index.ts
var INDEX_VERSION = 1;
var WIKILINK_RE = /\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g;
var VaultIndex = class {
  constructor(app, getSettings, persist, load) {
    this.app = app;
    this.getSettings = getSettings;
    this.persist = persist;
    this.load = load;
    this.data = {
      version: INDEX_VERSION,
      updatedAt: 0,
      notes: {}
    };
    this.building = false;
  }
  get entries() {
    return this.data.notes;
  }
  async init() {
    const loaded = await this.load();
    if (loaded?.version === INDEX_VERSION && loaded.notes) {
      this.data = loaded;
    }
    const debounced = (0, import_obsidian.debounce)(() => void this.fullRebuild(), 800, true);
    this.app.vault.on("create", (f) => {
      if (f instanceof import_obsidian.TFile && f.extension === "md") debounced();
    });
    this.app.vault.on("modify", (f) => {
      if (f instanceof import_obsidian.TFile && f.extension === "md") debounced();
    });
    this.app.vault.on("delete", (f) => {
      if (f instanceof import_obsidian.TFile && f.extension === "md") debounced();
    });
    this.app.vault.on("rename", () => debounced());
  }
  async fullRebuild() {
    if (this.building) return;
    this.building = true;
    try {
      const settings = this.getSettings();
      const files = this.app.vault.getMarkdownFiles();
      const notes = {};
      const outMap = {};
      for (const file of files) {
        if (isExcludedPath(file.path, settings)) continue;
        const content = await this.app.vault.cachedRead(file);
        const title = this.extractTitle(file, content);
        const titleKey = normalizeTitleKey(title);
        const prefix = normalizePrefix(this.stripFrontmatter(content));
        const out = this.extractOutLinks(content, file.path);
        outMap[file.path] = out;
        notes[file.path] = {
          path: file.path,
          mtime: file.stat.mtime,
          title,
          size: file.stat.size,
          outLinks: out.size,
          inLinks: 0,
          titleKey,
          prefixHash: simpleHash(prefix),
          tags: this.extractTags(content),
          hasAvoidance: hasAvoidanceMarkers(content) || hasAvoidanceMarkers(title)
        };
      }
      const pathByBasename = /* @__PURE__ */ new Map();
      for (const p of Object.keys(notes)) {
        const base = basenameTitle(p).toLowerCase();
        const arr = pathByBasename.get(base) ?? [];
        arr.push(p);
        pathByBasename.set(base, arr);
      }
      for (const [from, targets] of Object.entries(outMap)) {
        for (const raw of targets) {
          const resolved = this.resolveLink(raw, from, notes, pathByBasename);
          if (resolved && notes[resolved] && resolved !== from) {
            notes[resolved].inLinks += 1;
          }
        }
      }
      this.data = {
        version: INDEX_VERSION,
        updatedAt: Date.now(),
        notes
      };
      await this.persist(this.data);
    } finally {
      this.building = false;
    }
  }
  extractTitle(file, content) {
    const m = /^#\s+(.+)$/m.exec(content);
    if (m) return m[1].trim();
    return basenameTitle(file.path);
  }
  stripFrontmatter(content) {
    if (!content.startsWith("---")) return content;
    const end = content.indexOf("\n---", 3);
    if (end === -1) return content;
    return content.slice(end + 4);
  }
  extractTags(content) {
    const tags = /* @__PURE__ */ new Set();
    const fm = content.startsWith("---") ? content.slice(3, content.indexOf("\n---", 3) + 1) : "";
    const tagLine = /tags:\s*\[([^\]]*)\]/i.exec(fm);
    if (tagLine) {
      for (const t of tagLine[1].split(",")) {
        const v = t.trim().replace(/^["']|["']$/g, "");
        if (v) tags.add(v.replace(/^#/, ""));
      }
    }
    const inline = content.matchAll(/(^|\s)#([\w\p{L}\p{N}/_-]+)/gu);
    for (const m of inline) tags.add(m[2]);
    return [...tags];
  }
  extractOutLinks(content, fromPath) {
    const set = /* @__PURE__ */ new Set();
    let m;
    const re = new RegExp(WIKILINK_RE.source, "g");
    while ((m = re.exec(content)) !== null) {
      const target = m[1].trim();
      if (target) set.add(target);
    }
    const md = content.matchAll(/\]\(([^)]+\.md)\)/gi);
    for (const x of md) set.add(x[1].replace(/^\.\//, ""));
    void fromPath;
    return set;
  }
  resolveLink(raw, fromPath, notes, pathByBasename) {
    const cleaned = raw.replace(/\\/g, "/").replace(/\.md$/i, "");
    if (notes[cleaned + ".md"]) return cleaned + ".md";
    if (notes[cleaned]) return cleaned;
    const folder = fromPath.includes("/") ? fromPath.slice(0, fromPath.lastIndexOf("/")) : "";
    const rel = folder ? `${folder}/${cleaned}.md` : `${cleaned}.md`;
    if (notes[rel]) return rel;
    const base = cleaned.split("/").pop().toLowerCase();
    const candidates = pathByBasename.get(base);
    if (candidates?.length === 1) return candidates[0];
    return null;
  }
  /** Ensure index exists; rebuild if empty */
  async ensureReady() {
    if (Object.keys(this.data.notes).length === 0) {
      await this.fullRebuild();
    }
  }
};

// src/engine/scorer.ts
function buildDuplicateClusters(notes) {
  const byKey = /* @__PURE__ */ new Map();
  for (const n of Object.values(notes)) {
    if (n.titleKey) {
      const k = `t:${n.titleKey}`;
      const arr = byKey.get(k) ?? [];
      arr.push(n.path);
      byKey.set(k, arr);
    }
    if (n.prefixHash && n.size > 40) {
      const k = `p:${n.prefixHash}`;
      const arr = byKey.get(k) ?? [];
      arr.push(n.path);
      byKey.set(k, arr);
    }
  }
  const clusters = /* @__PURE__ */ new Map();
  for (const [k, paths] of byKey) {
    const uniq = [...new Set(paths)];
    if (uniq.length >= 2) clusters.set(k, uniq);
  }
  return clusters;
}
function scoreNotes(notes, settings, now = Date.now()) {
  const clusters = buildDuplicateClusters(notes);
  const pathToCluster = /* @__PURE__ */ new Map();
  for (const [ck, paths] of clusters) {
    for (const p of paths) {
      if (!pathToCluster.has(p) || ck.startsWith("t:")) {
        pathToCluster.set(p, ck);
      }
    }
  }
  const scored = [];
  for (const n of Object.values(notes)) {
    if (isSnoozed(settings.snoozeUntil[n.path], now)) continue;
    const daysStale = daysBetween(n.mtime, now);
    const signals = [];
    let score = 0;
    const w = settings.weights;
    if (daysStale < 3) continue;
    if (daysStale >= settings.staleDays) {
      signals.push("stale");
      const capped = Math.min(daysStale, 365);
      const staleScore = 40 * ((capped - settings.staleDays) / (365 - settings.staleDays + 1) + 0.3);
      score += w.stale * Math.min(40, Math.max(12, staleScore));
    }
    if (n.inLinks === 0) {
      signals.push("orphan");
      score += w.orphan * 30;
    }
    const ck = pathToCluster.get(n.path);
    if (ck) {
      signals.push("duplicate");
      score += w.duplicate * 25;
    }
    if (n.hasAvoidance) {
      signals.push("avoidance");
      score += w.avoidance * 10;
    }
    if (daysStale < 14) score *= 0.5;
    if (signals.length === 0 || score <= 0) continue;
    scored.push({
      path: n.path,
      title: n.title,
      score,
      signals,
      explain: buildExplain(signals, daysStale, n.inLinks, n.path),
      daysStale,
      inLinks: n.inLinks,
      clusterKey: ck
    });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored;
}
function buildExplain(signals, daysStale, inLinks, path) {
  const parts = [];
  if (signals.includes("stale")) parts.push(`Stale ${daysStale}d`);
  if (signals.includes("orphan")) parts.push("Orphan");
  if (signals.includes("duplicate")) parts.push("Duplicate");
  if (signals.includes("avoidance")) parts.push("Avoidance");
  const folder = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "/";
  parts.push(folder === "" ? "root" : folder);
  void inLinks;
  return parts.join(" \xB7 ");
}

// src/engine/queue.ts
function targetCount(settings) {
  if (settings.sessionTargetCount === "auto") {
    return Math.min(20, Math.max(5, Math.floor(settings.sessionMinutes / 1.5)));
  }
  return Math.min(20, Math.max(1, settings.sessionTargetCount));
}
function buildTodayQueue(scored, settings) {
  const limit = targetCount(settings);
  const perFolder = /* @__PURE__ */ new Map();
  const perCluster = /* @__PURE__ */ new Map();
  const out = [];
  for (const note of scored) {
    if (out.length >= limit) break;
    const folder = parentFolder(note.path) || "(root)";
    const fCount = perFolder.get(folder) ?? 0;
    if (fCount >= settings.maxPerFolder) continue;
    if (note.clusterKey) {
      const c = perCluster.get(note.clusterKey) ?? 0;
      if (c >= 2) continue;
      perCluster.set(note.clusterKey, c + 1);
    }
    perFolder.set(folder, fCount + 1);
    out.push(note);
  }
  return out;
}

// src/session/schedule.ts
function shouldOfferCatchUpSession(settings, now = /* @__PURE__ */ new Date()) {
  if (!settings.scheduleEnabled) return false;
  if (settings.lastSessionDate === todayKey(now) && settings.lastSessionCompleted) {
    return false;
  }
  const t = parseScheduleTime(settings.scheduleTime);
  if (!t) return false;
  const scheduled = new Date(now);
  scheduled.setHours(t.h, t.m, 0, 0);
  return now.getTime() >= scheduled.getTime();
}
function msUntilNextSchedule(settings, now = /* @__PURE__ */ new Date()) {
  if (!settings.scheduleEnabled) return null;
  const t = parseScheduleTime(settings.scheduleTime);
  if (!t) return null;
  const next = new Date(now);
  next.setHours(t.h, t.m, 0, 0);
  if (next.getTime() <= now.getTime()) {
    next.setDate(next.getDate() + 1);
  }
  return next.getTime() - now.getTime();
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var PulseSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Vault Pulse" });
    containerEl.createEl("p", {
      text: "All processing is local. No AI. No network calls."
    });
    const s = this.plugin.settings;
    new import_obsidian2.Setting(containerEl).setName("Stale days").setDesc("Notes not modified for at least this many days can be flagged stale.").addText(
      (t) => t.setValue(String(s.staleDays)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.staleDays = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Session minutes").setDesc("Default focus session length (habit timebox).").addText(
      (t) => t.setValue(String(s.sessionMinutes)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.sessionMinutes = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Session target count").setDesc('Number of cards per session, or "auto" (~minutes/1.5, clamped 5\u201320).').addText(
      (t) => t.setValue(
        s.sessionTargetCount === "auto" ? "auto" : String(s.sessionTargetCount)
      ).onChange(async (v) => {
        if (v.trim().toLowerCase() === "auto") {
          s.sessionTargetCount = "auto";
        } else {
          const n = Number(v);
          if (!Number.isNaN(n) && n > 0) s.sessionTargetCount = Math.floor(n);
        }
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Exclude folders").setDesc("Comma-separated folder prefixes to ignore (e.g. Archive, Templates).").addText(
      (t) => t.setValue(s.excludeFolders.join(", ")).onChange(async (v) => {
        s.excludeFolders = v.split(",").map((x) => x.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Archive folder").setDesc("Archive action moves notes under this folder (year-month subfolder).").addText(
      (t) => t.setValue(s.archiveFolder).onChange(async (v) => {
        s.archiveFolder = v.trim() || "Archive/Pulse";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Snooze days").setDesc("How long Snooze hides a note from the queue.").addText(
      (t) => t.setValue(String(s.snoozeDays)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.snoozeDays = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Max notes per folder").setDesc("Diversity cap so one folder does not fill the queue.").addText(
      (t) => t.setValue(String(s.maxPerFolder)).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n > 0) {
          s.maxPerFolder = Math.floor(n);
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Daily habit schedule" });
    new import_obsidian2.Setting(containerEl).setName("Enable daily schedule").setDesc("When Obsidian is open at the set time, offer a session. Catch-up on next launch.").addToggle(
      (t) => t.setValue(s.scheduleEnabled).onChange(async (v) => {
        s.scheduleEnabled = v;
        await this.plugin.saveSettings();
        this.plugin.reschedule();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Schedule time").setDesc("Local 24h time, e.g. 21:00").addText(
      (t) => t.setValue(s.scheduleTime).onChange(async (v) => {
        s.scheduleTime = v.trim();
        await this.plugin.saveSettings();
        this.plugin.reschedule();
      })
    );
    containerEl.createEl("h3", { text: "Signal weights" });
    this.weightSetting(containerEl, s, "stale", "Stale weight");
    this.weightSetting(containerEl, s, "orphan", "Orphan weight");
    this.weightSetting(containerEl, s, "duplicate", "Duplicate weight");
    this.weightSetting(containerEl, s, "avoidance", "Avoidance weight");
    containerEl.createEl("p", {
      cls: "pulse-muted",
      text: `Streak: ${s.streakDays} day(s). Last session: ${s.lastSessionDate || "\u2014"}`
    });
  }
  weightSetting(containerEl, s, key, name) {
    new import_obsidian2.Setting(containerEl).setName(name).addText(
      (t) => t.setValue(String(s.weights[key])).onChange(async (v) => {
        const n = Number(v);
        if (!Number.isNaN(n) && n >= 0) {
          s.weights[key] = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  staleDays: 90,
  sessionMinutes: 20,
  sessionTargetCount: "auto",
  excludeFolders: ["Archive", "Templates", "attachments", ".trash"],
  archiveFolder: "Archive/Pulse",
  snoozeDays: 7,
  scheduleEnabled: false,
  scheduleTime: "21:00",
  weights: {
    stale: 1,
    orphan: 1,
    duplicate: 1,
    avoidance: 1
  },
  maxPerFolder: 3,
  snoozeUntil: {},
  streakDays: 0,
  lastSessionDate: "",
  lastSessionCompleted: false
};

// src/ui/session-modal.ts
var import_obsidian3 = require("obsidian");
var SessionModal = class extends import_obsidian3.Modal {
  constructor(app, queue, handlers) {
    super(app);
    this.index = 0;
    this.timerId = null;
    this.closed = false;
    this.queue = queue;
    this.handlers = handlers;
    this.remainingSec = Math.max(60, handlers.minutes * 60);
    this.stats = {
      opened: 0,
      archived: 0,
      snoozed: 0,
      skipped: 0,
      target: queue.length
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("pulse-session-modal");
    contentEl.createEl("h2", { text: "Vault Pulse session" });
    this.timerEl = contentEl.createDiv({ cls: "pulse-timer" });
    this.statusEl = contentEl.createDiv({ cls: "pulse-status" });
    this.cardEl = contentEl.createDiv({ cls: "pulse-card" });
    const actions = contentEl.createDiv({ cls: "pulse-actions" });
    new import_obsidian3.Setting(actions).addButton(
      (b) => b.setButtonText("Open").setCta().onClick(() => void this.act("open"))
    ).addButton(
      (b) => b.setButtonText("Archive").onClick(() => void this.act("archive"))
    ).addButton(
      (b) => b.setButtonText("Snooze").onClick(() => void this.act("snooze"))
    ).addButton(
      (b) => b.setButtonText("Skip").onClick(() => void this.act("skip"))
    );
    new import_obsidian3.Setting(contentEl).addButton(
      (b) => b.setButtonText("End session").onClick(() => this.finish(false))
    );
    this.renderCard();
    this.tickTimer();
    this.timerId = window.setInterval(() => this.tickTimer(), 1e3);
  }
  onClose() {
    if (this.timerId != null) window.clearInterval(this.timerId);
    if (!this.closed) {
      this.closed = true;
      this.handlers.onComplete(this.stats, this.isSuccess());
    }
  }
  tickTimer() {
    if (this.remainingSec <= 0) {
      this.finish(true);
      return;
    }
    const m = Math.floor(this.remainingSec / 60);
    const s = this.remainingSec % 60;
    this.timerEl.setText(
      `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")} remaining`
    );
    this.remainingSec -= 1;
  }
  renderCard() {
    const done = this.stats.opened + this.stats.archived + this.stats.snoozed + this.stats.skipped;
    this.statusEl.setText(
      `Card ${Math.min(this.index + 1, this.queue.length)} / ${this.queue.length} \xB7 processed ${done}`
    );
    this.cardEl.empty();
    if (this.index >= this.queue.length) {
      this.cardEl.createEl("p", {
        text: "Queue complete. Great work \u2014 end session or wait for the timer."
      });
      return;
    }
    const note = this.queue[this.index];
    this.cardEl.createEl("h3", { text: note.title });
    this.cardEl.createEl("p", { cls: "pulse-explain", text: note.explain });
    this.cardEl.createEl("p", {
      cls: "pulse-path",
      text: note.path
    });
  }
  async act(action) {
    if (this.index >= this.queue.length) return;
    const note = this.queue[this.index];
    try {
      await this.handlers.onAction(note, action);
    } catch (e) {
      console.error(e);
      new import_obsidian3.Notice("Pulse action failed. See console.");
      return;
    }
    if (action === "open") this.stats.opened += 1;
    if (action === "archive") this.stats.archived += 1;
    if (action === "snooze") this.stats.snoozed += 1;
    if (action === "skip") this.stats.skipped += 1;
    this.index += 1;
    if (this.index >= this.queue.length) {
      this.finish(true);
      return;
    }
    this.renderCard();
  }
  isSuccess() {
    const done = this.stats.opened + this.stats.archived + this.stats.snoozed + this.stats.skipped;
    return this.stats.target > 0 && done / this.stats.target >= 0.5;
  }
  finish(auto) {
    if (this.closed) return;
    this.closed = true;
    if (this.timerId != null) window.clearInterval(this.timerId);
    this.handlers.onComplete(this.stats, this.isSuccess());
    if (auto) new import_obsidian3.Notice("Pulse session time is up.");
    this.close();
  }
};

// src/ui/pulse-view.ts
var import_obsidian4 = require("obsidian");
var PULSE_VIEW_TYPE = "vault-pulse-view";
var PulseView = class extends import_obsidian4.ItemView {
  constructor(leaf) {
    super(leaf);
    this.queue = [];
    this.onStart = null;
    this.onRefresh = null;
  }
  getViewType() {
    return PULSE_VIEW_TYPE;
  }
  getDisplayText() {
    return "Vault Pulse";
  }
  getIcon() {
    return "activity";
  }
  setHandlers(opts) {
    this.onStart = opts.onStart;
    this.onRefresh = opts.onRefresh;
  }
  setQueue(queue) {
    this.queue = queue;
    this.render();
  }
  async onOpen() {
    this.render();
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("pulse-view");
    root.createEl("h2", { text: "Vault Pulse" });
    root.createEl("p", {
      cls: "pulse-muted",
      text: "Local radar for notes worth triaging. No AI. No network."
    });
    const toolbar = root.createDiv({ cls: "pulse-toolbar" });
    const startBtn = toolbar.createEl("button", {
      text: "Start session",
      cls: "mod-cta"
    });
    startBtn.onclick = () => this.onStart?.();
    const refreshBtn = toolbar.createEl("button", { text: "Rebuild queue" });
    refreshBtn.onclick = () => void this.onRefresh?.();
    root.createEl("h3", { text: `Today\u2019s queue (${this.queue.length})` });
    if (this.queue.length === 0) {
      root.createEl("p", {
        text: "No signals right now. Rescan after more notes age, or lower Stale days in settings."
      });
      return;
    }
    const list = root.createEl("ul", { cls: "pulse-queue-list" });
    for (const n of this.queue) {
      const li = list.createEl("li");
      const title = li.createEl("div", { cls: "pulse-q-title", text: n.title });
      title.setAttr("title", n.path);
      li.createEl("div", { cls: "pulse-q-explain", text: n.explain });
      li.createEl("div", {
        cls: "pulse-q-score",
        text: `score ${n.score.toFixed(1)}`
      });
    }
  }
};

// src/main.ts
var VaultPulsePlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS, weights: { ...DEFAULT_SETTINGS.weights }, snoozeUntil: {}, excludeFolders: [...DEFAULT_SETTINGS.excludeFolders] };
    this.scheduleTimer = null;
    this.cachedQueue = [];
  }
  async onload() {
    await this.loadSettings();
    this.index = new VaultIndex(
      this.app,
      () => this.settings,
      async (data) => {
        await this.saveData({ settings: this.settings, index: data });
      },
      async () => {
        const raw = await this.loadData();
        return raw?.index ?? null;
      }
    );
    await this.index.init();
    this.registerView(PULSE_VIEW_TYPE, (leaf) => {
      const view = new PulseView(leaf);
      view.setHandlers({
        onStart: () => void this.startSession(),
        onRefresh: async () => {
          await this.rebuildQueue(true);
          this.refreshOpenViews();
        }
      });
      return view;
    });
    this.addRibbonIcon("activity", "Vault Pulse", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "pulse-start-session",
      name: "Start Pulse session",
      callback: () => void this.startSession()
    });
    this.addCommand({
      id: "pulse-open-view",
      name: "Open Pulse view",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "pulse-rescan",
      name: "Rescan vault index",
      callback: () => void this.rescan()
    });
    this.addSettingTab(new PulseSettingTab(this.app, this));
    void this.app.workspace.onLayoutReady(async () => {
      await this.index.ensureReady();
      await this.rebuildQueue(false);
      this.refreshOpenViews();
      this.reschedule();
      if (shouldOfferCatchUpSession(this.settings)) {
        new import_obsidian5.Notice("Vault Pulse: catch-up session available. Run \u201CStart Pulse session\u201D.");
      }
    });
  }
  onunload() {
    if (this.scheduleTimer != null) {
      window.clearTimeout(this.scheduleTimer);
      this.scheduleTimer = null;
    }
    for (const leaf of this.app.workspace.getLeavesOfType(PULSE_VIEW_TYPE)) {
      leaf.detach();
    }
  }
  async loadSettings() {
    const raw = await this.loadData();
    if (raw?.settings) {
      this.settings = {
        ...DEFAULT_SETTINGS,
        ...raw.settings,
        weights: { ...DEFAULT_SETTINGS.weights, ...raw.settings.weights },
        excludeFolders: raw.settings.excludeFolders ?? [...DEFAULT_SETTINGS.excludeFolders],
        snoozeUntil: raw.settings.snoozeUntil ?? {}
      };
    }
  }
  async saveSettings() {
    const raw = await this.loadData();
    await this.saveData({
      settings: this.settings,
      index: raw?.index ?? null
    });
  }
  reschedule() {
    if (this.scheduleTimer != null) {
      window.clearTimeout(this.scheduleTimer);
      this.scheduleTimer = null;
    }
    const ms = msUntilNextSchedule(this.settings);
    if (ms == null) return;
    this.scheduleTimer = window.setTimeout(() => {
      new import_obsidian5.Notice("Vault Pulse: scheduled triage time.");
      void this.startSession();
      this.reschedule();
    }, ms);
  }
  async rescan() {
    new import_obsidian5.Notice("Vault Pulse: scanning vault\u2026");
    await this.index.fullRebuild();
    await this.rebuildQueue(false);
    this.refreshOpenViews();
    new import_obsidian5.Notice("Vault Pulse: scan complete.");
  }
  async rebuildQueue(forceRescan) {
    if (forceRescan) await this.index.fullRebuild();
    else await this.index.ensureReady();
    const scored = scoreNotes(this.index.entries, this.settings);
    this.cachedQueue = buildTodayQueue(scored, this.settings);
  }
  refreshOpenViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(PULSE_VIEW_TYPE)) {
      const v = leaf.view;
      if (v instanceof PulseView) v.setQueue(this.cachedQueue);
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(PULSE_VIEW_TYPE);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf?.setViewState({ type: PULSE_VIEW_TYPE, active: true });
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      await this.rebuildQueue(false);
      this.refreshOpenViews();
    }
  }
  async startSession() {
    await this.rebuildQueue(false);
    if (this.cachedQueue.length === 0) {
      new import_obsidian5.Notice("Vault Pulse: nothing to triage right now.");
      return;
    }
    const queue = [...this.cachedQueue];
    new SessionModal(this.app, queue, {
      minutes: this.settings.sessionMinutes,
      onAction: (note, action) => this.handleAction(note, action),
      onComplete: (stats, completed) => void this.finishSession(stats, completed)
    }).open();
  }
  async handleAction(note, action) {
    if (action === "open") {
      const file = this.app.vault.getAbstractFileByPath(note.path);
      if (file instanceof import_obsidian5.TFile) {
        await this.app.workspace.getLeaf(false).openFile(file);
      }
      return;
    }
    if (action === "snooze") {
      this.settings.snoozeUntil[note.path] = addDaysIso(this.settings.snoozeDays);
      await this.saveSettings();
      return;
    }
    if (action === "skip") return;
    if (action === "archive") {
      const file = this.app.vault.getAbstractFileByPath(note.path);
      if (!(file instanceof import_obsidian5.TFile)) return;
      const dest = archiveTargetPath(note.path, this.settings.archiveFolder);
      const folder = dest.slice(0, dest.lastIndexOf("/"));
      await this.ensureFolder(folder);
      let finalDest = dest;
      if (this.app.vault.getAbstractFileByPath(finalDest)) {
        const stamp = Date.now();
        const base = note.path.split("/").pop().replace(/\.md$/i, "");
        finalDest = `${folder}/${base}-${stamp}.md`;
      }
      await this.app.fileManager.renameFile(file, finalDest);
      new import_obsidian5.Notice(`Archived \u2192 ${finalDest}`);
    }
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let cur = "";
    for (const p of parts) {
      cur = cur ? `${cur}/${p}` : p;
      if (!this.app.vault.getAbstractFileByPath(cur)) {
        await this.app.vault.createFolder(cur);
      }
    }
  }
  async finishSession(stats, completed) {
    const today = todayKey();
    if (completed) {
      if (this.settings.lastSessionDate === today) {
      } else {
        const yesterday = /* @__PURE__ */ new Date();
        yesterday.setDate(yesterday.getDate() - 1);
        if (this.settings.lastSessionDate === todayKey(yesterday)) {
          this.settings.streakDays += 1;
        } else {
          this.settings.streakDays = 1;
        }
      }
    }
    this.settings.lastSessionDate = today;
    this.settings.lastSessionCompleted = completed;
    await this.saveSettings();
    await this.rebuildQueue(false);
    this.refreshOpenViews();
    const done = stats.opened + stats.archived + stats.snoozed + stats.skipped;
    new import_obsidian5.Notice(
      `Pulse done: ${done}/${stats.target} \xB7 open ${stats.opened} \xB7 archive ${stats.archived} \xB7 snooze ${stats.snoozed} \xB7 skip ${stats.skipped} \xB7 streak ${this.settings.streakDays}`
    );
  }
};
